language:
  - cpp

dist: xenial

sudo: false

compiler:
  - gcc

before_install:
  - readonly PARENT_DIR=$(pwd)
  # build from source latest eigen
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - cd eigen-git-mirror
  - mkdir build && cd build && cmake ../ && make && sudo make install

# install:

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake

script:
  - cd ${PARENT_DIR}
  - mkdir build
  - cd build
  - cmake -DBUILD_EXAMPLES=ON ../
  - cmake --build .
  - make test

notifications:
  email: false
